name: Container deploy
on: 
  push:
    branches:
        - main
        - dev
env:
  CACHE_KEY: node-deps

jobs:
  test-container:
    runs-on: ubuntu:latest
    container:
      image: node:16
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
